[tool.poetry]
name = "canvasapi"
version = "0.1.0"
description = ""
authors = ["Nico de Groot <ndegroot0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
